import requests
import subprocess
import os

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "qwen2.5-coder:3b"
SOURCE_FILE = "src/main/java/com/example/App.java"

def read_error_log(path="build.log"):
    if not os.path.exists(path):
        return "No build.log found."
    with open(path, "r", errors="ignore") as f:
        content = f.read()
    return content[-4000:]

def read_source_file():
    with open(SOURCE_FILE, "r") as f:
        return f.read()

def ask_llm_for_fixed_file(error_log, current_code):
    prompt = (
        "You are a CI/CD auto-fix assistant. A Maven build failed with the "
        "following error log:\n\n"
        f"{error_log}\n\n"
        "Here is the current content of the source file that caused the error:\n\n"
        f"{current_code}\n\n"
        "Return ONLY the corrected, complete Java file content. "
        "Do not include explanations, markdown formatting, or code fences. "
        "Just the raw corrected source code, ready to be written directly to the file."
    )
    resp = requests.post(OLLAMA_URL, json={
        "model": MODEL,
        "prompt": prompt,
        "stream": False
    })
    resp.raise_for_status()
    return resp.json()["response"].strip()

def clean_code_fences(text):
    # in case the model still wraps it in ``` fences despite instructions
    lines = text.splitlines()
    if lines and lines[0].strip().startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip().startswith("```"):
        lines = lines[:-1]
    return "\n".join(lines)

def run(cmd):
    print(f"$ {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
    return result.returncode

if __name__ == "__main__":
    print("=== Healing Script Started ===")

    log = read_error_log()
    original_code = read_source_file()

    print("=== Asking Ollama for a fixed file ===")
    fixed_code = ask_llm_for_fixed_file(log, original_code)
    fixed_code = clean_code_fences(fixed_code)

    print("=== FIXED CODE ===")
    print(fixed_code)

    # Write the fix
    with open(SOURCE_FILE, "w") as f:
        f.write(fixed_code)

    # Create branch, commit, push, open PR
    branch = "auto-fix/build-failure"
    run(f"git checkout -b {branch}")
    run(f"git add {SOURCE_FILE}")
    run('git commit -m "Auto-fix: build failure resolved by Ollama"')
    run(f"git push -f origin {branch}")
    run(
        f'gh pr create --title "Automated fix for build failure" '
        f'--body "This PR was auto-generated by the healing script after a build failure. '
        f'Please review the change before merging." '
        f'--base main --head {branch}'
    )

    print("=== Healing Script Finished ===")
