import requests
import subprocess
import os

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "qwen2.5-coder:3b"
SOURCE_FILE = "src/main/java/com/example/App.java"
REPO = "sivashankarm6405/self-healing-demo"

def read_error_log(path="build.log"):
    if not os.path.exists(path):
        return "No build.log found."
    with open(path, "r", errors="ignore") as f:
        content = f.read()
    return content[-4000:]

def read_source_file():
    with open(SOURCE_FILE, "r") as f:
        return f.read()

def ask_llm_for_fixed_file(error_log, current_code):
    prompt = (
        "You are a CI/CD auto-fix assistant. A Maven build failed with the "
        "following error log:\n\n"
        f"{error_log}\n\n"
        "Here is the current content of the source file that caused the error:\n\n"
        f"{current_code}\n\n"
        "Return ONLY the corrected, complete Java file content. "
        "Do not include explanations, markdown formatting, or code fences. "
        "Just the raw corrected source code, ready to be written directly to the file."
    )
    resp = requests.post(OLLAMA_URL, json={
        "model": MODEL,
        "prompt": prompt,
        "stream": False
    })
    resp.raise_for_status()
    return resp.json()["response"].strip()

def clean_code_fences(text):
    lines = text.splitlines()
    if lines and lines[0].strip().startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip().startswith("```"):
        lines = lines[:-1]
    return "\n".join(lines)

def run(cmd, env=None):
    print(f"$ {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, env=env)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
    return result.returncode

if __name__ == "__main__":
    print("=== Healing Script Started ===")
    run('git config --global user.email "jenkins@localhost"')
    run('git config --global user.name "Jenkins Healing Bot"')

    branch = "auto-fix/build-failure"

    git_user = os.environ.get("GIT_USER")
    git_token = os.environ.get("GIT_TOKEN")

    if not git_user or not git_token:
        print("ERROR: GIT_USER / GIT_TOKEN not found in environment. Check Jenkinsfile withCredentials block.")
        exit(1)

    log = read_error_log()
    original_code = read_source_file()

    print("=== Asking Ollama for a fixed file ===")
    fixed_code = ask_llm_for_fixed_file(log, original_code)
    fixed_code = clean_code_fences(fixed_code)

    print("=== FIXED CODE ===")
    print(fixed_code)

    with open(SOURCE_FILE, "w") as f:
        f.write(fixed_code)

    branch = "auto-fix/build-failure"

    # Explicit authenticated remote URL — no dependency on stored credentials
    auth_remote = f"https://{git_user}:{git_token}@github.com/{REPO}.git"

    run(f"git checkout -B {branch}")   # -B forces recreate if it already exists
    run(f"git add {SOURCE_FILE}")
    run('git commit -m "Auto-fix: build failure resolved by Ollama"')
    run(f"git push -f {auth_remote} {branch}")

    # Set GH_TOKEN so gh CLI authenticates non-interactively, no dependency on `gh auth login`
    env = os.environ.copy()
    env["GH_TOKEN"] = git_token

    run(
        f'gh pr create --title "Automated fix for build failure" '
        f'--body "This PR was auto-generated by the healing script after a build failure. '
        f'Please review the change before merging." '
        f'--base main --head {branch} --repo {REPO}',
        env=env
    )

    print("=== Healing Script Finished ===")
